### ISSUE TITLE
Git tag all releases (missing tag for latest release 3.10.4 on google-play)

### ISSUE THREAD

**Issue by emanuelb** [monya-wallet/monya#129]
https://play.google.com/store/apps/details?id=org.missmonacoin.monya
Show: Current Version: 3.10.4
while latest tag/releases in this repo is v3.10.3:
https://github.com/monya-wallet/monya/releases
https://github.com/monya-wallet/monya/tags

The related commit for 3.10.4 releases is probably:
https://github.com/monya-wallet/monya/commit/8f8f188ea5d787c194abac601a9f87476cf509ee

Please tag all releases that are published to google-play and upload .apk file to them, see issue: #126

**Comment by MissMonacoin** [comment]
Good catch!
I created release. 
Thank you.

**Comment by emanuelb** [comment]
Same issue now with the release 3.10.5 on google play https://play.google.com/store/apps/details?id=org.missmonacoin.monya 
latest tag is for previous release 3.10.4 https://github.com/monya-wallet/monya/tags
