### ISSUE TITLE
請求一覧の編集のplaceholderについて

### ISSUE THREAD

**Issue by kazu0617** [monya-wallet/monya#17]
金額(日本円)と書かれているが、法定通貨を米ドルに変更しても請求書の画面にて日本円扱いで登録される。
EX: 法定通貨を米ドルに変更
→ 請求一覧の編集で 放送権 / 500(円) と入力して[保存]
→ 請求書を作成で右上から[放送権]を選択
→ 500USDとして登録される

**Comment by MissMonacoin** [comment]
フィアット欄はデータ型には用意してあるんだけど、めんどくさいので、いい感じのPR出してくれませんか？
