### ISSUE TITLE
Coin derivation vuln.

### ISSUE THREAD

**Issue by Nyanko-Kota** [monya-wallet/monya#20]
I think that key derivation of NEET is unsafe.
The derivation number of BIP 44 seems to be conflicted with a BTC one.
Since the secret key is the same, there is a possibility of NEET being stolen when BTC is stolen. But if this number changes immediately, neet hodler will lose their neet. Thus, I highly suggest NEET should be separated into addcoins/index.html

**Comment by MissMonacoin** [comment]
I certainly confirmed this issue.
BTC:https://github.com/monya-wallet/monya/blob/36cf270e59064e102463e463f3e5786cac497764/js/currencyList.js#L86
NEET: https://github.com/monya-wallet/monya/blob/36cf270e59064e102463e463f3e5786cac497764/js/currencyList.js#L257
These number are the same zero.

**Comment by raspi0124** [comment]
So, do you mean that if I am securing Bitcoins secret but not securing it for neetcoin, then I might get hacked and get stolen my Bitcoin using neetcoins secret?
well.... I think you have to separate it immediately @MissMonacoin .

**Comment by MissMonacoin** [comment]
This problem is not so dangerous and does not affect right now.
It only affects when either BTC or NEET private key is stolen.
It is much more dangerous that master passphrase is stolen.
But monya states high security so this is a little concern.
I would have checked NEET PR closer. I'm sorry.

**Comment by MissMonacoin** [comment]
IMO It's ok to announce that storing both BTC and NEET is unsafe.
But do all BTC hodler listen to my announcement?
Do they separate wallet passphrase?

**Comment by MissMonacoin** [comment]
I determined to move NEET to addcoins/index.html
If there is no objection, I will move it.
If you have an objection, please write comment here.

**Comment by Nyanko-Kota** [comment]
I think there is no problem. 
Dear Yuki,

**Comment by MissMonacoin** [comment]
yes.
You needn't issue slip44 number.

**Comment by MissMonacoin** [comment]
I changed private key zero into 2002.
