### ISSUE TITLE
Impossible to refund at Atomic Swap page on Firefox

### ISSUE THREAD

**Issue by nao20010128nao** [monya-wallet/monya#21]
The tabs in the bottom of Atomic Swap page don't switch [on web version](https://monya-wallet.github.io/wallet/).    
- Browser: Firefox 59.0.1+build1-0ubuntu0.17.10.1
- OS: Linux lesmi-NLC170 4.13.0-37-generic #42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

*ADDED:* Cannot reproduce on Chrome

# Evidence
*NOTE:* It's clicking a lot
https://youtu.be/JzAkfFgbKJc

**Comment by MissMonacoin** [comment]
This is because Onsen UI doesn't fully support Firefox.
I fixed it by adding a hack.
