### ISSUE TITLE
NEMのブロックチェーンエクスプローラーに渡すトランザクションハッシュが「undefined」となる

### ISSUE THREAD

**Issue by fkfk** [monya-wallet/monya#23]
NEM画面の「履歴」をタップするとブロックチェーエクスプローラーが開きますが、URLを見ると http://explorer.nemchina.com//#/s_tx?hash=undefined となります。
トランザクションのハッシュが取得できていないようです。

**Comment by MissMonacoin** [comment]
Merged.
Thank you!
