### ISSUE TITLE
getAddressPropが返すbalanceの値がinsight APIとblockbook APIで異なる

### ISSUE THREAD

**Issue by fkfk** [monya-wallet/monya#65]
# 該当箇所

[insight API](https://github.com/monya-wallet/monya/blob/e5578690e513b0d086702c45a8932a2e407b274f/js/explorers/insight.js#L58)
[blockbook API](https://github.com/monya-wallet/monya/blob/e5578690e513b0d086702c45a8932a2e407b274f/js/explorers/blockbook.js#L113)

# 問題となる挙動

`getAddressProp`の第一引数(`propName`)に`balance`を指定した場合、insight APIの場合は`balanceSat`の値を返すようですが、blockbook APIの場合は`balance`の値を返すようです。
MONAを例にすると、1MONA所持しているアドレスのbalanceを取得しようとした際にinsight APIだと`100000000`を返しますが、blockbook APIだと`"1"`を返します。

# この挙動による影響

[モナパトークンを送る前に残高をチェックする箇所](https://github.com/monya-wallet/monya/blob/master/component/sendToken.js#L81)で、blockbook APIだと規定額(50000wat)に満たないとして警告ダイアログが表示されます。

**Comment by fujiwaraizuho** [comment]
了解しました
blockbook.js にて修正させて頂きます

**Comment by fkfk** [comment]
単純にblockbook.js側で`propName`見て`balance`だったらsat単位に直す、として良いのなら後でPR投げておきます
