### ISSUE TITLE
CI build failed.

### ISSUE THREAD

**Issue by cryptcoin-junkey** [monya-wallet/monya#91]
See https://circleci.com/gh/monya-wallet/monya/516 .

**Comment by cryptcoin-junkey** [comment]
```
cp: cannot stat 'docs/wallet/*': No such file or directory
```

It was caused by copying files in the removed directory, even though I have no idea why previous builds are succeeded.

**Comment by fujiwaraizuho** [comment]
Thanks.
Fixed in this commit
https://github.com/monya-wallet/monya/commit/6dc27ea9154048df0f74ea82f8e046d5f4540326
